export const actionTypes={
    USER_LOGIN:"USER_LOGIN",
    LOGIN_FAIL:"LOGIN_FAIL",
    USER_LOGOUT:"USER_LOGOUT",
    USER_REGISTER:"USER_REGISTER",
    USER_REGISTER_FAIL:" USER_REGISTER_FAIL",
    LOAD_USER:"LOAD_USER",
    NO_USER:"NO_USER"

}